name: eels
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - ipywidgets
  - tensorflow=2.11.0
  - hyperspy=1.7.3
  - scikit-learn
  - scipy=1.7.1
  - seaborn
  - pandas